---
title: Air Zone Summary Report
header-includes:
  - \usepackage[table,xcdraw]{xcolor}
  - \usepackage{multicol}
  - \usepackage{booktabs}
  - \usepackage{makecell}
  - \usepackage{multirow}
  - \usepackage{colortbl}
  - \usepackage{amsmath}
output:
  pdf_document:
    md_extensions: +raw_attribute
    latex_engine: lualatex
mainfont: Arial
params:
  ozone_summary_plot: !r ambient_summary_plot
  ozone_caaqs_mgmt_map: !r management_map
  ozone_caaqs_mgmt_chart: !r management_chart
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("ggplot2")
```

<!-- TODO: Air zone map -->

<!-- Air zone management framework table -->

```{=latex}
\begin{table}[h]
\caption{Air zone management framework for ground-level ozone and PM$_{2.5}$. The CAAQS define the upper threshold, separating the "red" and "orange" management levels.}
\begin{tabular}{|l|c|c|c|c|c|c|}
\hline
\rowcolor[HTML]{D9D9D9}
& \multicolumn{2}{c|}{\begin{tabular}[c]{@{}c@{}}$\text{O}_3$\\ (ppb)\end{tabular}} & \multicolumn{2}{c|}{\begin{tabular}[c]{@{}c@{}}$\text{PM}_{2.5}$ – Annual\\ ($\mu \text{g/m}^3$)\end{tabular}} & \multicolumn{2}{c|}{\begin{tabular}[c]{@{}c@{}}$\text{PM}_{2.5}$ - 24h\\ ($\mu \text{g/m}^3$)\end{tabular}} \\ \cline{2-7}
\rowcolor[HTML]{D9D9D9} 
\multirow{-2}{*}{Management Level} & 2015 & 2020 & 2015 & 2020 & 2015 & 2020 \\ \hline
\rowcolor[HTML]{A50026}
{\color[HTML]{FFFFFF} Red} & \multicolumn{6}{c|}{\cellcolor[HTML]{A50026}{\color[HTML]{FFFFFF} Actions for Achieving Air Zone CAAQS}} \\ \hline
Threshold (CAAQS) & 63 & 62 & 10 & 8.8 & 28 & 27 \\ \hline
\rowcolor[HTML]{F46D43}
Orange & \multicolumn{6}{c|}{\cellcolor[HTML]{F46D43}Actions for Preventing CAAQS Exceedance} \\ \hline
Threshold & \multicolumn{2}{c|}{56} & \multicolumn{2}{c|}{6.4} & \multicolumn{2}{c|}{19} \\ \hline
\rowcolor[HTML]{FEE08B}
Yellow & \multicolumn{6}{c|}{\cellcolor[HTML]{FEE08B}Actions for Preventing Air Quality Deterioration} \\ \hline
Threshold & \multicolumn{2}{c|}{50} & \multicolumn{2}{c|}{4} & \multicolumn{2}{c|}{10} \\ \hline
\rowcolor[HTML]{A6D96A}
Green & \multicolumn{6}{c|}{\cellcolor[HTML]{A6D96A}Actions for Keeping Clean Areas Clean} \\ \hline
\end{tabular}
\end{table}
```

<!-- Ozone summary plots -->

```{r ozone_summary_plot, fig.width = 4, fig.asp = 1.4, fig.cap = "Air zone summary plot for 8-hour average ozone"}
params$ozone_summary_plot +
  theme(text = element_text(size = 8))
```

```{r ozone_caaqs_mgmt_map, fig.width = 3, fig.asp = 1, fig.cap = "Management level map for ozone."}
params$ozone_caaqs_mgmt_map
```

```{r ozone_caaqs_mgmt_chart, fig.width = 4, fig.asp = 1, fig.cap = "Management level achievement chart for ozone."}
params$ozone_caaqs_mgmt_chart +
  theme(
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    legend.title = element_text(size = 10)
  )
```

<!-- TODO: PM2.5 summary plots -->
