---
output: 
  pdf_document:
    latex_engine: lualatex
    keep_md: true
    fig_caption: true
    includes:
      in_header: components/header.tex
mainfont: Arial
params:
  ozone: !r ozone_caaqs_results
  annual_ozone: !r ozone_caaqs$ann_4th_highest
  o3_az: !r ozone_az
  ems_ids_ozone: !r NA
  pm25: !r pm_caaqs_combined_results
  annual_pm25: !r pm25_caaqs_annual$yearly_avg
  pm25_az: !r az_ambient
  pm25_mgmt: !r az_mgmt
  ems_ids_pm25: !r NA
  airzone: "Lower Fraser Valley"
title: "`r params$airzone` Air Zone"
---

<!-- Load functions, filter data to airzone -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.width = 6)

## Load packages, functions, etc.
source("components/functions.R")

## Filter data to air zone
airzone <- params$airzone
ozone <- filter(params$ozone, airzone == !!airzone)
pm25 <- filter(params$pm25, airzone == !!airzone)

# Get airzone-level metrics
o3_az <- filter(params$o3_az, airzone == !!airzone)
pm25_az <- filter(params$pm25_az, airzone == !!airzone)
pm25_mgmt <- filter(params$pm25_mgmt, airzone == !!airzone)

## Filter annual data to EMS ids provided if present, otherwise use the same
## ones as in the summary data
if (!is.na(params$ems_ids_ozone)) {
  annual_ozone <- filter(params$annual_ozone, ems_id %in% params$ems_ids_ozone)
} else {
  annual_ozone <- filter(params$annual_ozone, ems_id %in% ozone$ems_id)
}
if (!is.na(params$ems_ids_pm25)) {
  annual_pm25 <- filter(params$annual_pm25, ems_id %in% params$ems_ids_pm25)
} else {
  annual_pm25 <- filter(params$annual_pm25, ems_id %in% pm25$ems_id)
}

```

```{r, echo=FALSE, results='asis'}
res <- knitr::knit_child("children/intro.Rmd", 
                         envir = environment(), 
                         quiet = TRUE)
cat(res, sep = "\n")
```


```{r, echo=FALSE, results='asis'}
res <- knitr::knit_child("children/ozone.Rmd", 
                         envir = environment(), 
                         quiet = TRUE)
cat(res, sep = "\n")
```

<!-- Ozone by station -->

```{r ozone-by-station, fig.height = 6, fig.cap = ozone_by_station_cap(airzone, ozone)}
plot_ozone_by_station(ozone, airzone)
```

<!-- Annual trends in ozone concentrations -->

```{r annual-ozone, fig.cap = annual_ozone_cap(annual_ozone)}

plot_ozone_station_timeseries(annual_ozone, airzone)

```

```{r, echo=FALSE, results='asis'}
res <- knitr::knit_child("children/pm25.Rmd", 
                         envir = environment(), 
                         quiet = TRUE)
cat(res, sep = "\n")
```

<!-- PM2.5 by station -->

```{r pm25-by-station, fig.height=8, fig.cap = pm25_by_station_cap(airzone, pm25)}
plot_pm25_by_station(pm25)
```

<!-- PM Annual trends in PM 2.5 -->

```{r annual-pm25, fig.cap = annual_pm25_cap(annual_pm25)}
plot_pm25_station_timeseries(annual_pm25, airzone)
```

```{r, echo=FALSE, results='asis'}
res <- knitr::knit_child("children/aqms.Rmd", 
                         envir = environment(), 
                         quiet = TRUE)
cat(res, sep = "\n")
```
