---
title: Georgia Strait Air Zone
header-includes:
  - \usepackage{booktabs}
  - \usepackage{makecell}
  - \usepackage{multirow}
  - \usepackage{colortbl}
  - \usepackage{xcolor}
  - \usepackage{textcomp}
output:
  pdf_document:
    latex_engine: lualatex
    fig_caption: true
mainfont: Arial
params:
  ozone: !r ozone_caaqs_results
  annual_ozone: !r ozone_caaqs$ann_4th_highest
  pm25: !r pm_caaqs_combined_results
  pm25_24h: !r pm_24h_caaqs_results
  annual_pm25: !r pm25_caaqs_annual$yearly_avg
  stations: !r stations_az
  airzone: "Georgia Strait"
---

```{r setup, echo = FALSE, message = FALSE}
## Source plotting and table functions. Also loads packages.
source("functions.R")

## Filter data to air zone
airzone <- params$airzone
ozone <- filter(params$ozone, airzone == !!airzone)
pm25 <- filter(params$pm25, airzone == !!airzone)

## Filter and add station names to annual ozone
annual_ozone <- params$annual_ozone %>%
  left_join(params$stations, by = c("ems_id", "station_name")) %>%
  filter(airzone == !!airzone)

## Filter and add station names to annual pm25
annual_pm25 <- params$annual_pm25 %>%
  left_join(params$stations, by = c("ems_id", "station_name")) %>%
  filter(airzone == !!airzone)  
```

<!-- Ozone by station -->

```{r ozone-by-station, echo = FALSE, warn = FALSE, fig.cap = paste0("Ozone concentrations in the ", airzone, " Air Zone, based on annual 4th highest daily 8-hour maxima, averaged over ", min(ozone$min_year, na.rm = TRUE), "-", max(ozone$max_year, na.rm = TRUE), ". Red dashed line identifies the CAAQS of 63 ppb.")}
plot_ozone_by_station(ozone, airzone)
```

<!-- Annual trends in ozone concentrations -->

```{r annual-ozone, echo = FALSE, warning = FALSE, fig.cap = paste0("Annual trends in ozone concentrations (", min(annual_ozone$year, na.rm = TRUE), "-", max(annual_ozone$year, na.rm = TRUE), "), based on annual 4th highest daily 8-hour maxima for a single year. Red dashed line identifies CAAQS of 63 ppb.")}

plot_ozone_station_timeseries(annual_ozone, airzone)
```

<!-- PM2.5 by station -->

```{r pm25-by-station, echo = FALSE, warning = FALSE, fig.asp = 1.3, fig.cap = paste0("PM$_{2.5}$ concentrations in the ", airzone, " Air Zone. Upper plot based on 24-hour concentration (annual 98th percentile, averaged over ", min(pm25$min_year, na.rm = TRUE), "-", max(pm25$max_year, na.rm = TRUE), "). Lower plot based on annual mean concentration (averaged over ", min(pm25$min_year, na.rm = TRUE), "-", max(pm25$max_year, na.rm = TRUE), "). Red dashed lines identify CAAQS of 28 $\\mu$g/m$^3$ (upper plot) and 10 $\\mu$g/m$^3$ (lower plot).")}
plot_pm25_by_station(pm25)
```

<!-- PM Annual trends in PM 2.5 -->

```{r annual-pm25, echo = FALSE, warning = FALSE, fig.cap = paste0("Trends in PM$_{2.5}$ concentrations (", min(annual_pm25$year, na.rm = TRUE), "-", max(annual_pm25$year, na.rm = TRUE), "), based on annual mean concentrations from a single year. The CAAQS value of 10 $\\mu$g/m$^3$ is shown by the dashed line. PM$_{2.5}$ measurements prior to 2011 are reported at 25\\textdegree C and 1 atm. From 2011 onward, measurements are reported at local conditions. ")}
plot_pm25_station_timeseries(annual_pm25, airzone)
```

## Table 2:  Summary of ozone concentrations as measured and air zone management levels for the `r airzone` Air Zone

```{r table-2, echo = FALSE}
create_ozone_table(ozone)
```

## Table 3: Summary of PM2.5 concentrations as measured and air zone management levels for the `r airzone` Air Zone

```{r table-3, echo = FALSE}
params$pm25_24h %>%
  filter(airzone == !!airzone) %>%
  create_pm25_table()
```
