---
title: Coastal Air Zone
header-includes:
  - \usepackage{booktabs}
  - \usepackage{makecell}
  - \usepackage{multirow}
  - \usepackage{colortbl}
  - \usepackage{xcolor}
  - \usepackage{textcomp}
  - \usepackage{float}
  - \floatplacement{figure}{H}
output:
  pdf_document:
    latex_engine: lualatex
mainfont: Arial
params:
  ozone: !r ozone_caaqs_results
  annual_ozone: !r ozone_caaqs$ann_4th_highest
  pm25: !r pm_caaqs_combined_results
  annual_pm25: !r pm25_caaqs_annual$yearly_avg
  stations: !r stations_az
  airzone: "Coastal"
---

<!-- Load functions, filter data to airzone -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

## Load packages
source("components/packages.R")

## Filter data to air zone
airzone <- params$airzone
ozone <- filter(params$ozone, airzone == !!airzone)
pm25 <- filter(params$pm25, airzone == !!airzone)

## Filter and add station names to annual ozone
annual_ozone <- params$annual_ozone %>%
  left_join(params$stations, by = c("ems_id", "station_name")) %>%
  filter(airzone == !!airzone)

## Filter and add station names to annual pm25
annual_pm25 <- params$annual_pm25 %>%
  left_join(params$stations, by = c("ems_id", "station_name")) %>%
  filter(airzone == !!airzone)  
  
## Source plotting and table functions
source("components/functions.R")
```

<!-- Ozone by station -->

```{r ozone-by-station, fig.align = "center", fig.asp = 1, out.width = "90%", fig.cap = ozone_by_station_cap(airzone, ozone)}
plot_ozone_by_station(ozone, airzone)
```

<!-- Annual trends in ozone concentrations -->

```{r annual-ozone, fig.cap = annual_ozone_cap(annual_ozone)}
plot_ozone_station_timeseries(annual_ozone, airzone)
```

<!-- PM2.5 by station -->

```{r pm25-by-station, fig.asp = 1.3, fig.cap = pm25_by_station_cap(airzone, pm25)}
plot_pm25_by_station(pm25)
```

<!-- PM Annual trends in PM 2.5 -->

```{r annual-pm25, fig.cap = annual_pm25_cap(annual_pm25)}
plot_pm25_station_timeseries(annual_pm25, airzone)
```

<!-- Summary of ozone concentrations as measured and air zone management levels -->

```{r table-2}
create_ozone_table(ozone, airzone)
```

<!-- Summary of PM2.5 concentrations as measured and air zone management levels -->

```{r table-3}
create_pm25_table(pm25, airzone)
```
