knitr::opts_chunk$set(echo = FALSE, warning = FALSE, dev = "pdf")

## Custom hook to generate wrapped figures. Unfortunately we can't just set the
## fig.env chunk option to "wrapfigure" because of the need to specify the
## alignment and width of the figure, so we use this hook instead. When using
## this, the fig.show option must be set to "hide" or else you will get two
## versions of each figure (the one generated normally by knitr and the one
## generated by this function). Note this has only been tested for one plot per
## chunk.
knitr::knit_hooks$set(wrapfigure = function(before, options, envir) {
  if (!before) {
    imgpath <- paste0(options$fig.path, options$label, "-1")
    return(
      paste(
        "\\begin{wrapfigure}{", options$position, "}{", options$out.width ,"}\n",
        "\\includegraphics{", imgpath, "}\n",
        "\\caption{", options$fig.cap, "}\n",
        "\\end{wrapfigure}",
        sep = ""
      )
    )
  }
})
