## Northeast Air Zone

The Northeast Air Zone is one of seven broad air zones across B.C. It is located in the northeast region of the province bordering the Rocky Mountains to the west, Alberta to the east, and Yukon and the Northwest Territories to the north The Northeast Air Zone includes the cities and communities in the Peace River Regional District including Fort St. John, Dawson Creek, Fort Nelson, the Districts of Chetwynd, Tumbler Ridge, Taylor, and Hudson’s Hope, the Village of Pouce Coupe; and the Treaty 8 First Nations communities of Blueberry River, Doig River, Halfway River, Prophet River, Saulteau, West Moberly and McLeod Lake. The largest population centre, Fort St. John, is home to the Ministry-operated air quality monitoring station. Other monitoring stations in the air zone are operated to monitor industrial activities such as oil and gas, and forestry products processing.  

#### Major Municipalities

The top five most populous cities/towns in the Northeast Air Zone are:

```{r,echo=FALSE,warning=FALSE,message=FALSE,results='hide'}
library(dplyr)
library(kableExtra)
df_cities <- readr::read_csv('https://raw.githubusercontent.com/bcgov/air-zone-reports/master/data/out/cities.csv')

tbl_cities <- df_cities %>%
  filter(airzone == 'Northeast')  %>%
  select(Name,C1_COUNT_TOTAL) %>%
  rename(Municipality = Name, `Population (2021)` = C1_COUNT_TOTAL) %>%
  arrange(desc(`Population (2021)`)) %>%
  ungroup() %>%
  dplyr::slice_head(n=5)

nrow(tbl_cities)
```
